# Generated by Django 4.0 on 2021-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('work', models.CharField(default='null', max_length=50)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comp',
            },
        ),
        migrations.CreateModel(
            name='Crudp',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Hometown', models.CharField(max_length=30)),
                ('Occupation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crudp',
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('Company_name', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('work', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
